# coding:utf-8
'''
1371. 每个元音包含偶数次的最长子字符串
    给你一个字符串 s ，请你返回满足以下条件的最长子字符串的长度：每个元音字母，即 'a'，'e'，'i'，'o'，'u' ，在子字符串中都恰好出现了偶数次。
'''

class Solution(object):
    def findTheLongestSubstring(self, s):
        '''
        使用滑动窗口
        '''
        def is_ok(ok_dict):
            for v in ok_dict.values():
                if v%2 == 1:
                    return False
            return True

        def init_ok(s1):
            ok_dict = {'a': 0, 'e': 0, 'i': 0, 'o': 0, 'u': 0}
            for i in s1:
                if ok_dict.has_key(i):
                    ok_dict[i] += 1
            return ok_dict

        def update_ok(ok_dict, i):
            if ok_dict.has_key(i):
                ok_dict[i] -= 1

        size = len(s)
        max_len = 0
        for low in range(size):
            high = size - 1
            if (high + 1 - low) <= max_len:
                break
            max_str = s[low:(high + 1)]
            ok_dict = init_ok(max_str)
            while high >= low:
                if (high+1-low) <= max_len:
                    break
                if is_ok(ok_dict):
                    max_len = high + 1 - low
                update_ok(ok_dict, s[high])
                high -= 1

        return max_len



if __name__ == '__main__':
    solution = Solution()
    print solution.findTheLongestSubstring("eleetminicoworoep")
    print solution.findTheLongestSubstring("id")
    print solution.findTheLongestSubstring("bpgmxrkhdcvxbnogftqgqmqlghlvsyyckbobtfejpbsqcsmcmzqsujmilpbrpanjsxkzetsrictzzylnmqzassdbsqadkklyrbulscpucrokqzrafklgesesdmkqnlkitlbwcyuhziymrjsztccwfincejrxuihgdixpbxqjzzgrcrkkjqebolzxbaknxfrbwswvuqnfghdsesqdxiogzbloktxlhuaapbfirbahycqfbqggojhpqlkmucgtfgvtjsntplapadvusvtnwskkcungwqzptsvrqptvxsyotpfivqjsyzmtriijatybzoolhqogwpkwuemnbudlzaiyrxbjmakkjszbgwckdvuceywjntkhauwwfyyyqxsuljjmnqozcgnhtbthuhhwmmgtexjxxlawwvjopfvealnrkzqpktdsujzrvinajycupdqhtxuxinlzhbdtqqqfejbcgavbnxwacbabrkkzatargpgijsrqihfgmbhrwobkkndasfqucyfghfjzdbzkxecoehbxjlbscogzhvfdbgbxxdczzxhjwiqnhxbxiygklloyvtmvmcnhpkftudhcyznirjkylnollkmpqalejfjserwxefouueefctihlukfipjcnerlodevkcvfprbbxgulxlqlzquzvlkudfmbitwzgbhjksmhlybhjwsagdehlqiefhcjsqqrtrznosqpfqlgnzcighyeeygafplfbzlcthvwgcouugtkfswvwagkprbblprlepcqkvxsvjtkzscpkncicvukafkhkiijpnajfujbdnntgilyuxspsjtivfkeldmlqxswgmoepwhbxuhcxcbqqpspwkqzfswpmam")
    exmaple = "vajsdzaxodxrquzrorcisoluxuvqjjtnqoxeqmkzxavcvzigbtdeoupeaxrwvmwmkakssyantkfncgyymjsxzdgdmfiivivdphgyzfxzzbohboqinxkuakbfmbkjkcmndfvhcbkejdfebthjjpmhhmqglloqmgbohyxbzoaqvhjfnwzzkekyrhtoujujjiqibvoqivhuoaszuoodknxgdzzntcjweiphbbskbqtyxkbocneswavlukdxpjushdylmhqeniexfcnjccbedefitvimlbsqqgqvgipfryentxtcupuibvqrlwltkyibnmeyqmauejjctwnpjhfoihfrfqfzjfjsnnzvqiiwrflnlgibxrerhcngcphmkujslvafrqxguduaiwpnupjpsvsymfldsibhhonnmuipjzvictawhehixuhlacbzbgzyhxcsvstjpqsisswnaypgnzttmaoqitkdrdzeqtaiizcqcquqtcvrxfbltgamditwtkxlmqrryzxwfpuaglejpurmwnocztqmkzjmdnrdrrtdjzezpvytpibojwdlcbohotigndowiougijfmxyvepgcbttonxtrruaogjfurlzmoplbihbkrvxgohwtndnurtzsqxnccxvrcbpslfljhihudfmjtvqqdojwyuycnqrerjfhzmdcesvntkpunaahsgxtkckwqldoruigypnthpatvaeladuvdfqazqyjrugqphxiydkbnztdphwhhridlloqdsrlsklinwrltrgrmyysrnvrccpnrfxsubskjdhuywwakyfnhkzzjecwxxywensyxodzogfrbdbbpruxftedtttqxmqzmubsvtwmbjvvcmatktbuexxtcoxxhklevaqbufkuqjubfasppnandszgxgksvngvfceebzmzvxczprgrzaztoyaikkatuxtthohocygeujxblzwqqgnfdkbyucljrzzxbsseixoibimnkxavhypfbjizhgdbnyoflplskcffnipxzzfnjxhmtigmlvfjcpvmkuggaceijfdiygamspablbewnprgphxiwtrjfacmgfycpmtinqtyltedihsfzrlpdhpixrezpnfpzchslxtblfgcchmrbpaxwfgczeaozaqdccttiezoepiwklrxdzttqerboukqxctbznotmzrknaidhbjoscyvooqgjtkpbkronsbgpwpeadaizfkuttdcuzcuduabubjfunhdfuqrnzzanmicurayevloptssqjhrzmcvmadnldbdebuxjvqrrjdaqdzmjnliiwabcopesurqnzmvjyrpeuzdylwdfuiefwiqctuwncqruaifgblcghikavgtrbcsbzjgflwsrhmgvoabbvnwdpwfutqopzkohqdnchskmmgrcwdjqqxoiymucwgclzzbumluaqvlpvcnhawxrynuihlvhqocakmupphnurggrtlzrofkfkvumjlexdcbcsdomlmtgczdoxoawcqubsjsgmlpsxywyzkwxnmbkiejqzpxjbzscdyumlkgxgyfubfwvcdaxjhnrqenptdlwxkqojrttwgmfceiakmloktiwmsxhktcovohqyhjwcswlvpfksvsttgnnaqumgozmrtfzbbakscltmgtwlojcicowyrfwncaozdlypprbgczghwziqcyfrkqfbruvamydltxndgsotgprjkzlliawkutiepyjyvyhcjlqkgvmxmhfsbmioywzbmmyagutwswpvlvqrwpxuwuhvuvcpvemqwifarabzujyumjwsenuimxntljtpjzhnujqxsujzmzalqgksykytnvsmbrjvfmbanbjxjnzoblexhawxyztbagaidjyvvvspatgtnuogxdnvohoijsvisrjafyiwrsqybkjfgqdeutzooprrwzkicnjjcmhphkygoztuxjqwgcokliosfaennnzcmfekgpcjjshlwhefzukpquckjvkqkgbmdvdvlzgkcqzidriguyztzvmwoormvrqfirqnpmxtkdpoebixfrjbmjyzdgafucnzhgqhgtmffjjmartvervejrndnvyqwvrsossdxyedohoxjpcusftslixxdzqqmenawihmencnfjnxqmbdlzjkchzzbrfzpgimorjcwtolirihvsdwdshifpbcbbrquiyemtuqejyzkkecvpknipkovlulxrufugjyzzelucbnmnuwstyplwjhwcdfrbcjdoozslqynlnfkzynrfarhzcvjualuehvnosynesznnvmpjdlhcuhhzrrhuhpuacqnmdcmjbtksyjdrgrqnnvukdhbmcuhmivianumvjflxpmgzuafnqerkiyqsnqkhhyzxkroyohtuqonrhsofctajiwwoiiqptemrakynhceisjwzvucrryhxsfznepximftmrcbuxkvezxhbfbckwhcpmebphutbmvpidilmkbudesfixoccqsbogrcptizjzmfsifeyxiuvbineurlibjatooiktscsnscwntfgzkregyuopcotahekrejlgmlwjxiofayutpqzntsfnrkoztcvkzvwkxpnozqgiliiewhjsqjcbiscrisjplvwvwiqpxzkqceidqlhvkmddpzovpwswicyenugneqonhdjnnybvrbrovzbstvlvzptpwzmjdikztkyxkvarvposeztlzqxfbseyyfomyqsvksfuxiatjlgvklgyhqtjsrdfinfxltzkggdphrqqjigyazvyqnvinrjhgcouulklejvalvfezhybvgydlcxerqardtzraqnyawxukrevohjarilfglrlttunjvcnhnxzckhbtevuhcosuspzyxnhjfyuhmuczcgmuiwdvkodfxsacgikwslmbakdvbufliipqsjtfvrubodsprjgrxedvkkepkrhshwzmfzwqpixmfssgmaqgkkckmcgktzzigxjgwapjnfhbdphjeyeqyqcrzypdvkvbzmyzfzyrkjcqgqgttgpgxqbfodzvdkxkuuigmsbdbzagcdbxlcgaoahcygdldbeqjbnqgqffzctdkuzhvutnhotwwuagajtfwnhsifoagmjgvcjtxtbhkdpkcplskbamioidwhtxuimmtvuqyfneeahbyisgpdsppngdrfiabecantkgbibbhvglkxdbyqeyrzrjfowacqyfxrxaaubnokjpzykakrklirjvvwmhkdljrptwrpuylrflknsimdkxagjwcnueywtchdwphtxbzziprwbbrnxqoutmpzmdnpjhxumgipkbddhtqgiwipklrcomvikpjzpxjorhkrkglpyrqgrxfblwjhsigzjoivbxendyiphjrgliiwcbutqdvrnkeazqswdzckphjotzswzgpaexxxblzgxrxchhoxyrccabzpecjoyyawsuthzjaoopyrvyaaggjynbrkkgkaxutaywdafpwdxqiyoxujfpsklmitsuejjfuqzpljnsdgcdisjltrtogbqkkcclddmxsbtxodbchucxujvbodpdbgihpblwtynlktyhivcqzocwjadkghieunfobqlzkfvorxfsizoztphhvixfkoruvrbaflicjbhdwlqikozjyjlzypwcelvlfzcftxzlgfzaxnzttsukrxpmhkoypvagwprdfxkotedqxqmtqnfizacdatharhmkvsjjdaqfeufjropxtxyvthbnxrjjgaiuepjkydlgkxpfpllcthkijkntuwytcfwfstcxhnqjtryrktohbugkjlkdawoypqozslwmerknhblstdrsfgqtrmkfefiueschmbmidtouujpjrhhbtwzbtqvtdpugoaulkswacaxtpoksnousgjgnfvusmkeeoqceadapjqthqkictaytthpkgahwfsemnunlrwsixxdgdaxxmnisjsuuubsrdkesvhxxjibkxybxrkafdfflajwtsounxiqoulafkugsmooxkiylqgrgpjfxvsxxqssnyqyhmydaydhhenkplyeuzcacwgzrxaheyhzidddiklvysgwgkgjpgsilzyqfkzwdrgcpxxkxblqofiqkziebzwchlimwmywotvrsoywrevgcvdsoxrpmequgbqdxirldjccepypnxvfutbghqkrzrphalafjeiiqolmwncfogjzazqzqvhelmneknxvwizzmuhkgpyunlbzzhvhgnumemcitrmcxvkazktmjbthajqlrxxntnzkxfouxhioratppdmomcubfmbrqzdntkfwkheolqwoaithdlzcsjhblrstfrnnhpokeosbwlhzsaeaedklxjmfzyjgixdytipzperkkjcgovcmdrpscoexdbqnryhztufqqpvfowwdimddncsylgnoustuiobokbwnxxywyguuwluqkxhyjmrtnfratfbsbvgsyejiwrbbivscrzbkgvcpbkisqvdvovkfhgcyqhwgdepghlcxpdeteksndcpomtdnqpchlxxdznoexfqttehmpmmmlfwoaeaogslsnvpgbuefqbwbnfchsxdhshjhctlojzfblkmlgacsnorgktobehatzyteutbeugoattemaitcdyicrkncsmofalnkvdtguxrnibxgeannlqhoigcwwszunkqtfeermszvmbalpnfyzvqinjereeblkxcvcpaeilsladmyadjzjjfcahdzbuerwpgpmcsrazttzthyrdcyalywjtdksttykfmuclpsyynkxoforgedkvvvvxncngmjqdyfohtueeujemcuchixhdthuwxnrapsilwyuaebvobzmjelundeondtcwlswyvdxjebyyeueyobrfrbrrsujnjywnxcapjznzihaeaeunidzplziewvbxrrsimbwrlhmtoqarpwyreqttgiqtaebgjxottwitqwibznmojuqukrqxrrnuzehvuxbpmhcouyqjrviuumqaeohwqoouktghtmeudwpihgtjxvtmtjxoonngvemmorcrrkckwnytlermkxzuffygljhlqgyxhndicxeofsrlcdzoqswtqwemhxbtzufzuaqpesaerasdzuukgjzjauvwqcigzydcpbljhpxxxeuttozbixbuczwjovrfxmmwaekydifffcxnxcqpyvskekqwsbjgseflunfvguaoxummtqioepdcnqjwtcnjxyaliygfejhnevdfmglaucnzgpvaxyblzrbgechsvxudxykfmeknojreuzwziesvqnlhnlybfkkskczstlcfgciozbamfbpjlwwqtnmatfjtfpnwopdqgdqxtjfsmmnvwqxzrzqtuhtkgcfxgldgwzsqfemigtnmntnhlwodrtnwpwfubwdqtrcauplzcdnuhzxcbqxbdbelwnqbgwxubxqiowltmmhrzdsbkwfasofcxduvnmloevkhsqjotnnlsfitzerukhvcdzdhfxsknuodwypeixomtriqnndwpsbxzqnhsylsvvgnveyosxhnlsvtozuroictfftgpppwqsugtmfeiaosnrxtekaxfvmmrrpsidvgacsumqsxtdimtttrmgszrjfqigquepbjfdiborpbdlyrtxesozcizmutztzryjalyvtenurbwrkqdpfzjqmodktzwbldciboswxjezxxaalzzucyeghcfzikklziirxhchjtauftudxdylenwqxzpcpuaiccnotseylzjzkihdwhodrvfaquzupbirflqbwrmzngjtgmhuobsjugvvpvzvtnfnxrokdcuktkfrlidubrqjfmcrlknfvwjmbwojfveseumkydnfsazsheqikrqtprrjehvcfydymcrxcpgppaidbgkrlxtbrupleijtlarbfvmaokjxygltbzuwwthjcevgxbxcergenvgrymborgqqrprfjljkekgocqnobcskfuesdhqyjkrglbroyynrcqpmbfpsqfkqcffvhopqfqzrpcyxlqibirkiiilctndgdgradhvhqyipiykewdhijysecihzweaamzjheouhudbvekznvsmdnycraygznhssjhruicryocefpwlnvqjrdkbkeixgonyzekcajydhpqndkhapivifhzvydvqupavrtcuwxdupegqnvdrnkblkzdahwvfbziyklmunssjazrewnwbwmfxqybdceudykvqrhhzefwfpfrhiyzjqwvyxpvkfyowiawlqutdbtkewofqukhyskgntrlkxddcrqgnbncehnewqeuzoewehremhsrgbokavbcbogjbvqrzasetwxlepuetdaeqmkvhsbtaubmojwdhpjopwanjhoduggtffsrtbzrqbnojmsjkzeahprgekuwfizmymkcpgxolspmfekscaxvomrbsjmserulyuxueugjutortoemqqwktakkqhwylikjefcovfthmsfyaxqhozvuchucoubdyxxdpourukzjtbarbwtywgxovbglzjsepqmfdtvpumkyfqudiqdiudiztvpucytugtmqtbbowlicjjgklimykrkpylwuuomqwftghyijztuozeiuktqrcewegimpgohoixpkyidokkqlavctrkokpawrkngvmxglqvblzwikfasiqmkxayzszembjwemmoekxnqimcvruinjaxycofdysfkfrrfsisbuuljsutixcnixcekostehvdnnxtbjqpeubtjmztapuuobrymqyrtykvfsqokuqrrwnowyqjeafpyjwfxbcbmhoxmjctdtklmbbgfrereybajgfdbgxfkrlvoetqbrarthytdqjpaqrherzltprtbeyudakbysrleabrxeewxvwdcefrzmlkeaznpmdfftcxcgzjsrdodpvpscfevyiohmuqwwhwpzytaakhicsvmdksgwdtcchsqudtosyfwqtvmuedwhpwlpokljzrdkmxffmlsmjwyxnsgzjaigywjumvrandmirxeqjmafxjqubkyjlrtgxcyoqcacfrjimvmecdxsntbtwrkhcwcjkwfrlviweznxguehidpfgyenurhdzgegwlhcjxhuehzhicifjbhhirdxjcrexsmfcoifcxbfziexgxsxtlrtcnwqyrwpsrjnyinxpwjtqjeglipmvssuqmzarmqtrzpgokaoayznaylwnjkmumpgejtmrnbrfqxbwadshvmmpirvyfreiswwnkijkvtxjwhcdknmrarjezjcivcleyznctmenevyphnuwacfypgasnhngvozjdaumylatsfzcputfvsepcmrpbbzkrorokeitsbrhleflarqnhbdwknbruukfhtszbifsdgdevokxdhsvopnucakxfezhmefdikgbmivebdwntfkcaccirzwbmfcmzqkbwzlfybabxegliadnsujyerdkgqravsudjphnzfxupkjndhraguqrlxihgvdmgjgkjzweuwmndsvgfajrqwxzuefjtocaiyuqxfhcpkxrdbwkzgmaqgoeavhplknuvmlnfypxewbhezkqganmkladbghulhbsjfjbzlimzlvxrbghzsijigqweigqqbuwwaiprhqvfklsjtfnjpjunlzvfjvotlozuaujwmjxcvtlvohpjqkmexmaoteckylkluiiiipvuzmmlfqvbfelscbpiieerlgdpvctheliitbnlxakqwfhfoctakabuxumijmosjlpnsiifomluzziazzkuqhgkpxlhyefvlzibujtphxwtpfwmeokddzyyfazvogulbpxjrmixtemqhuafystviiojvxvnveagigsxvuaqfbayjpfgfcjefjlnklugybinwtheomzfazetscgzupaawplxnslwnbjsdmkzfcxdiuzesshdcxcoagakutsjvnxdleqltgiqubadflsqvdtaqejucnacxitwqttzzphssrvklzwhwbiwixcnqlhdmvuysywmiquilvbawvsxycxkggfjgqkmjmvhjfnwpfupnnkxzlczjuicheoenkwnkfhgjrndslukpunvkakdlazyrojusilluurbcaklmstogrtgktbygfxuqosrrmgqixulltknguawwaeumbqdmjvbyarnpbmtjzrdtzn"
    print solution.findTheLongestSubstring(exmaple)



